services:
  - type: web
    name: contact-form-app
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: "postgresql://neondb_owner:npg_Y4tic2DSKljq@ep-wispy-wildflower-a5i4lebr-pooler.us-east-2.aws.neon.tech/neondb?sslmode=require"
      - key: JWT_SECRET
        sync: false
        